language: python
cache: pip
sudo: false
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
matrix:
  allow_failures:
    - python: 2.6
before_install:
  - pip install -U pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py nosetests --with-coverage --cover-package=pssh
after_success:
  - coveralls
deploy:
  provider: pypi
  user: pkittenis
  password:
    secure: ZQJ41Nguc7Y5XHvtN8lITIiW1S1jvy0p50rssMUJpa9wVZIh0HcW0K/Xv2v17fDNuOvQlVbsF0sY/BmcRfH7c7nzwt7fRXGOjXbZk5djqwusKXL6zlVN7OKjAY6j2EByOjD9UpDDkB5tDqb4lRBCX87wknii/t+7/8P0ddoBojM=
  on:
    tags: true
  distributions: sdist bdist_wheel
  repo: ParallelSSH/parallel-ssh
